language: lisp
sudo: required

env:
  matrix:
    - LISP=sbcl

install:
  - if [ -x ./install.sh ] && head -2 ./install.sh | grep '^# cl-travis' > /dev/null;
    then
      ./install.sh;
    else
      curl https://raw.githubusercontent.com/luismbo/cl-travis/master/install.sh | sh;
    fi

script:
  - sbcl --non-interactive --load tests.lisp
